### ISSUE TITLE
no response

### ISSUE THREAD

**Issue by hassman12** [Tommrodrigues/homebridge-http-lock-mechanism#3]
hi,
thanks for the plugin
i have an esp connected to the lock, when he gets "X.X.X.X/OPEN" the appropriate the digital io goes to HIGH and vice versa.
when i connected your plugin the accessory shows me "no response"
any idea?
thanks

**Comment by phenotypic** [comment]
Hi, that's strange. Can you confirm whether "No Response" appears immediately after Homebridge startup or whether it happens when you try to change the state of the lock? 

It would also be helpful if you could attach a copy of your `config.json` (just the part for the lock) and an extract from your Homebridge logs when "No Response" appears - are there any errors?

It is also quite possible that your device is not responding with the correct response code after receiving the request. The device should instantly response with a `200` HTTP response code.

**Comment by hassman12** [comment]
thank you
thats the thing - my device does not send the 200 response,
could you maybe tell me which lines i need to mark out so it will be ok?

**Comment by phenotypic** [comment]
Really depends which device you're using. If you're using the Arduino IDE to program an ESP8266, you can take a look at one of my Node-MCU scripts [here](https://github.com/Tommrodrigues/homebridge-nodemcu-boiler/blob/master/NodeMCU-Boiler.ino) (lines `197` - `199`). 

Otherwise, just have a look for some guides specific to your device and see how they handle HTTP requests.

Best, Tom

**Comment by hassman12** [comment]
hi,
what i meant was which lines do i need to markout from your code so that the 200 response will be indifferent. anyway - i am sending back a 200 response and the lock's status was still "no response".
the "no response" happens when i try to close the the lock.
my config was:
       "accessory": "HTTPLock",
       "name": "gate Lock",
       "openURL": "http://XXX/on_gate",
       "closeURL": "http://XXX/off_gate",
       "autoLock": true,
       "autoLockDelay": 3

at the end i figured it out with the help of your logs:
Jul 16 20:09:49 raspberrypi homebridge[504]: [7/16/2019, 8:09:49 PM] [gate Lock] Setting LockTargetState to 0
Jul 16 20:09:52 raspberrypi homebridge[504]: [7/16/2019, 8:09:52 PM] [gate Lock] Error setting LockTargetState: ETIMEDOUT
Jul 16 20:10:03 raspberrypi homebridge[504]: [7/16/2019, 8:10:03 PM] [gate Lock] Setting LockTargetState to 0
Jul 16 20:10:06 raspberrypi homebridge[504]: [7/16/2019, 8:10:06 PM] [gate Lock] Error setting LockTargetState: connect EHOSTUNREACH 10.0.1.87:80

so i added a 8000 mil sec timeout and now the status is coherent.

**Comment by phenotypic** [comment]
The problem is that the plugin is not hearing back from your device. Note the two errors listed: `ETIMEDOUT` and `EHOSTUNREACH`. Both errors indicate that either your device is unreachable or it is not responding to the requests. The best course of action would be to check whether the device is reachable by pinging it. If it is reachable, then the problem is with the device and not the plugin i.e. the device is not returning the correct response.

If your device is an ESP8266 running Arduino code and you are having problems trying to debug your code, feel free to attach or link to the code and I can have a quick look over it to see if I can spot the problem.
