### ISSUE TITLE
cmd command alternative

### ISSUE THREAD

**Issue by Nastras** [Tommrodrigues/homebridge-http-lock-mechanism#4]
Hello, great plugin you have there exactly what I was looking for. Unfortunately I am missing a little something. Is it possible that you can send a CMD command instead of a http command? 

I tried it but got this error

Error setting LockTargetState: Invalid URI "gatttool%20-t%20random%20-b%20F9:D2:3G:4C:D3:08%20--char-write-req%20-a%200x0016%20-n%20570100"

Would I be very happy if you could integrate that?

Best regards
Nastra

**Comment by phenotypic** [comment]
Hi there,

Unfortunately, as the plugin name suggests, this plugin is designed to work by making HTTP requests instead of executing commands. This is why you are getting the `Invalid URI` error: what you have specified as the URL is not a URL.

It is totally possible to make a plugin which executes commands instead of making HTTP requests, however, I have no incentive/time to make such a plugin. Of course, you are more than welcome to create your own plugin which does as you desire. Equally, a quick google search pulls up numerous pre-made plugins (like [this](https://github.com/entmike/homebridge-cmdaccessory) one) which appear to do just as you have specified.
