### ISSUE TITLE
Error parsing status: Unexected token

### ISSUE THREAD

**Issue by Flavien06** [Tommrodrigues/homebridge-http-lock-mechanism#8]
Hello,
Thank for plugin.
Not really important for works but I get this error:
`Error parsing status: Unexected token < in json at position 0`

how to avoid the error?

**Comment by phenotypic** [comment]
Hi there, you are getting this error because the plugin cannot interpret the `/status` response from your API. Your API is probably not returning a properly formatted JSON - see [API Interfacing](https://github.com/phenotypic/homebridge-http-lock-mechanism#api-interfacing) for reference.

Please can you include a copy of your `config.json` as well as the response from your API when you request `/status`.

**Comment by Flavien06** [comment]
Hi, ot,
I'm just executing a simple php page with no json or other return.
The php just activates a relay. The relay is always at 0. The page changes it to 1 for 1s then goes back to 0.
Is it possible to skip the return wait? Or what should I add in my PHP page? 

`{
    "accessory": "HTTPLock",
    "name": "Relais A",
    "apiroute": "http://192.168.x.x/relayA.php",
    "autoLock": true
}`

**Comment by phenotypic** [comment]
As I said previously, your API must behave according to the [API Interfacing](https://github.com/phenotypic/homebridge-http-lock-mechanism#api-interfacing) section of the `README`.

You cannot expect the plugin to work correctly if you do not adhere to these requirements.
