### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by frizby66** [Tommrodrigues/homebridge-http-lock-mechanism#9]
Is it possible to have a stateless option for a lock? I have a momentary input lock (single pulse) which can never be latched on and has no state feedback. Currently use http-switch, but obviously that shows as a switch, not a lock. Would love to use this plugin instead. Possible?

**Comment by phenotypic** [comment]
Hi there, I think the closest you can get to a stateless switch using this plugin would be to enable `autoLock` and have it so that your API would not respond to the `/setState?value=1` command.

That way, you can click the icon once in the Home app and have it 'auto-lock' after a set period without triggering a second pulse, giving the illusion of a stateless switch. I hope that helps.

**Comment by frizby66** [comment]
Hi, thanks for the info…is this the format to use?

`        {
            "accessory": "HTTPLock",
            "name": "Lock A",
            "apiroute": "http://192.168.2.15/cgi-bin/accessControl.cgi?action=openDoor&channel=1&UserID=101&Type=Remote",
            "auth": {
                "username": "xxxxx",
                "password": "xxxxx"
            },
            "autolock": "true",
            "autoLockDelay": "1"
        }, `

**Comment by phenotypic** [comment]
The username and password fields should not be nested inside the `auth` object. The rest of the formatting appears to be correct.

Please refer to the [API Interfacing](https://github.com/phenotypic/homebridge-http-lock-mechanism#api-interfacing) section of the README to see how the plugin expects to interface with your API.
